version: "3.8"

services:

    lbroundrobbin:
        build:
            context: .
            dockerfile: .docker/DBDockerfile
        container_name: lbroundrobbin
        environment:
            - PORT=45000
        ports:
            - "4567:45000"
        depends_on:
            - mongodb
            - logservice1
            - logservice2
            - logservice3

    logservice1:
        build:
            context: .
            dockerfile: .docker/LogSDockerfile
        container_name: logservice1
        environment:
            - PORT=35001
        ports:
            - "35001:35001"

    logservice2:
        build:
            context: .
            dockerfile: .docker/LogSDockerfile
        container_name: logservice2
        environment:
            - PORT=35002
        ports:
            - "35002:35002"

    logservice3:
        build:
            context: .
            dockerfile: .docker/LogSDockerfile
        container_name: logservice3
        environment:
            - PORT=35003
        ports:
            - "35003:35003"

    mongodb:
        image: mongo:5.0.25-focal
        container_name: mongodb
        environment:
            - MONGO_INITDB_DATABASE=mongodb
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        ports:
            - "27017:27017"
        command: mongod

volumes:
    mongodb:
    mongodb_config:
